### ISSUE TITLE
Possible issue with `get_all_timeslice_ids()`

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/hdf5libs#47]
Specifically, if I have a script on `np04-srv-004` which does the following:
```
#!/usr/bin/env python3                                                                                                        

from hdf5libs import HDF5RawDataFile

h5file = HDF5RawDataFile("/data1/test/tpstream_run017982_0000_tpwriter_tpswriter_20221117T153144.hdf5")
h5file.get_all_timeslice_ids()
```
then I get this:
```
Traceback (most recent call last):
  File "/nfs/sw/work_dirs/jcfree/daqbuild_rc-v3.2.1-1/./simple_file_check.py", line 6, in <module>
    h5file.get_all_timeslice_ids()
  File "/nfs/sw/work_dirs/jcfree/daqbuild_rc-v3.2.1-1/install/hdf5libs/lib64/python/hdf5libs/__init__.py", line 15, in get_all_timeslice_ids
    return sorted(super().get_all_timeslice_ids())
IndexError: stoi
```
...though this may be an issue with the file itself and not the function (which works fine on other files).

**Comment by jcfreeman2** [comment]
Issue determined to be with the file, due to its timestamps being around the max size of an unsigned 64-bit int
